### ISSUE TITLE
 extension failed while requesting for 'go.cd.elastic-agent.server-ping'

### ISSUE THREAD

**Issue by kernellius** [gocd-contrib/docker-swarm-elastic-agents#28] opened 2017-06-27 12:02 UTC
I cannot get the plugin to work with GoCD server 17.5.0 and plugin version 1.1.4.

I'm getting 
`2017-06-27 11:51:10,991 DEBUG [132@MessageListener for ServerPingListener] Printer:113 - com.thoughtworks.go.domain.Plugin{configuration={"environment_variables":"","docker_ca_cert":"","docker_uri":"http://192.168.235.30:2375","go_server_url":"https://192.168.235.30:8154/go","docker_client_key":"","max_docker_containers":"10","docker_client_cert":"","auto_register_timeout":"2"}, pluginId=cd.go.contrib.elastic-agent.docker-swarm, id=1}
2017-06-27 11:51:11,001 DEBUG [cancelHungJobThread] GO_MODE_AWARE_TIMER:41 - Server is in active state, Running: class com.thoughtworks.go.server.service.ScheduleService#cancelHungJobs
2017-06-27 11:51:11,012 ERROR [132@MessageListener for ServerPingListener] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener@333c4971
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.contrib.elastic-agent.docker-swarm' implementing 'elastic-agent' extension failed while requesting for 'go.cd.elastic-agent.server-ping'. Reason: [java.lang.RuntimeException: java.lang.NullPointerException]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:60)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:49)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:32)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:22)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:317)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:173)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        ... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:78)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:178)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:173)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        ... 10 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.refreshInstances(DockerPlugin.java:86)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:58)
        ... 13 more
Caused by: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.refreshAll(DockerServices.java:120)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.refreshInstances(DockerPlugin.java:84)
        ... 14 more
2017-06-27 11:51:11,195 DEBUG [consumeBuildCausesThread] GO_MODE_AWARE_TIMER:41 - Server is in active state, Running: class com.thoughtworks.go.server.service.ScheduleService#autoSchedulePipelinesFromRequestBuffer
2017-06-27 11:51:12,195 DEBUG [consumeBuildCausesThread] GO_MODE_AWARE_TIMER:41 - Server is in active state, Running: class com.thoughtworks.go.server.service.ScheduleService#autoSchedulePipelinesFromRequestBuffer`

**Comment by ketan** [comment] 2017-06-27 12:09
What's the output of `docker service ls -q | xargs -I ID docker service inspect ID`?

**Comment by ketan** [comment] 2017-06-27 12:10
Also the version of docker you are on.

**Comment by ketan** [comment] 2017-06-27 12:15
Note to self:

Suspicion is that [this line](https://github.com/gocd-contrib/docker-swarm-elastic-agents/blob/2441d0ea254291d11e03fd10f2c3937018ec96fc/src/main/java/cd/go/contrib/elasticagents/dockerswarm/elasticagent/DockerServices.java#L120) throws up because `service.spec()` likely returns a `null`.

**Comment by kernellius** [comment] 2017-06-27 13:42
there is no service agent running, I have the same error when the plugin try to create the service.

docker info:
`Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 61
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 7i8uqo01tu1yeaycyv5hy43zq
 Is Manager: true
 ClusterID: mcdpc9qy0d7egd6rfqga8xdry
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.235.30
 Manager Addresses:
  192.168.235.130:2377
  192.168.235.230:2377
  192.168.235.30:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.844GiB
Name: linux-host1
ID: UGKR:ROVR:4ADY:N7BF:NC5G:LZTN:AEUV:I4K4:G2WT:PTCE:3JYC:XVH2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 70
 Goroutines: 201
 System Time: 2017-06-27T09:41:35.183875939-04:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by ketan** [comment] 2017-06-27 13:51
> there is no service agent running, I have the same error when the plugin try to create the service.

That makes no sense. The line that's throwing the exception is [this](https://github.com/gocd-contrib/docker-swarm-elastic-agents/blob/v1.1.4/src/main/java/cd/go/contrib/elasticagents/dockerswarm/elasticagent/DockerServices.java#L120), since the line is in a loop, it very clearly implies that there is at least one service that `docker.listServices` (aka `docker service ls`) has returned.

Maybe there's a service that pops up and disappears quickly and does not show up in `docker service ls`; but shows up when the plugin repetitively does the equivalent.

If you add a log statement as the first line in the same loop to print the following and deploy the jar, it might help us debug and put a better fix in.

```
LOG.info("Service id" + service.id());
LOG.info("Service spec" + service.spec());
LOG.info("Service spec labels" + service.spec().labels());
```

**Comment by kernellius** [comment] 2017-06-27 14:04
this is the error I get on agent creation:

2017-06-27 13:57:57,504 ERROR [124@MessageListener for CreateAgentListener] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener@5c7d46fb
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.contrib.elastic-agent.docker-swarm' implementing 'elastic-agent' extension failed while requesting for 'go.cd.elastic-agent.create-agent'. Reason: [java.lang.RuntimeException: java.lang.NullPointerException]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:51)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:40)
        at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
        at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:317)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:173)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        ... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:78)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:178)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:173)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        ... 10 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.refreshInstances(DockerPlugin.java:86)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:55)
        ... 13 more
Caused by: java.lang.NullPointerException
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.refreshAll(DockerServices.java:120)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.refreshInstances(DockerPlugin.java:84)
        ... 14 more


I have an other issue where the log file for the plugin is not created.
All the other plugin logs works, but for this on I cannot get it work

**Comment by kernellius** [comment] 2017-06-27 18:50
I got it working on a fresh install of gocd server... but can't figure out why it doesn't work on our server.

**Comment by remy-tiitre** [comment] 2017-09-04 18:23
I have the same exception with custom GoCD docker container (I run GoCD Server inside docker container). So there might be some incorrect setup from my part, but the exception seems to be exactly the same. Plugin is 1.1.4, GoCD is 17.8.0 and docker is inside the container and on the host 17.06.1-ce, /var/run/docker.sock has been mapped to GoCD container. I tried to start the GoCD with docker-compose and as service in Swarm. This exception happened on both cases.

**Comment by bdpiparva** [comment] 2017-09-18 07:31
@remy-tiitre --- This is not reproducible at our end. I am closing the issue. Feel free to reopen this issue if you are facing this issue consistently.

**Comment by remy-tiitre** [comment] 2017-09-18 08:11
Can you make the guide how to setup this plugin with GoCD and its agents inside docker containers. For example, do you need to have to docker client installed inside the container, or its enough to map the /var/run/docker.sock from the host, etc

**Comment by remy-tiitre** [comment] 2017-09-19 10:24
Still get the exception when running GoCD server in docker container in a swarm mode:

**Comment by bdpiparva** [comment] 2017-09-19 12:37
@remy-tiitre --- Please can you provide you plugin-settings and elastic profile for the plugin with sensitive information redacted.

**Comment by remy-tiitre** [comment] 2017-09-19 13:41
These exceptions occure even when I have only docker-swarm-elastic-agents added to stock plugins and there is no elastic profile created.

**Comment by ketan** [comment] 2017-09-19 13:46
> These exceptions occure even when I have only docker-swarm-elastic-agents added to stock plugins and there is no elastic profile created.

The NullPointerException in `DockerClientFactory` seems to indicate that the plugin is not configured. I've opened #36 to fix this particular issue.

Once you configure the plugin, that exception should go away. If you're seeing a different exception than the one in the stack trace in this comment (https://github.com/gocd-contrib/docker-swarm-elastic-agents/issues/28#issuecomment-330496931), please provide that stacktrace.

**Comment by bdpiparva** [comment] 2017-09-19 13:49
@ketan This is already fixed [here](https://github.com/gocd-contrib/docker-swarm-elastic-agents/blob/master/src/main/java/cd/go/contrib/elasticagents/dockerswarm/elasticagent/PluginRequest.java#L48-L51). I am making new release of plugin.

**Comment by ketan** [comment] 2017-09-19 13:56
I don't see the exception being caught and logged differently. This will
merely change the NPE to a different exception. Can we catch that exception
here (
https://github.com/gocd-contrib/docker-swarm-elastic-agents/blob/master/src/main/java/cd/go/contrib/elasticagents/dockerswarm/elasticagent/DockerPlugin.java#L83)
and log it differently

**Comment by bdpiparva** [comment] 2017-09-19 14:07
I don't see any point in handling that `PluginSettingsNotConfiguredException` differently because on that exception plugin sends`Plugin settings is not configured.` error message to server.

**Comment by ketan** [comment] 2017-09-19 14:25
On Tue, Sep 19, 2017 at 7:39 PM Bhupendra <notifications@github.com> wrote:

> I don't see any point in handling that
> PluginSettingsNotConfiguredException differently because on that
> exception plugin sendsPlugin settings is not configured. error message to
> server.
>
I don't agree, this exception will be bubbled and printed along with a
stacktrace. I'm more concerned about the fact that a stacktrace seems to
indicate there's an error, when in reality it's not an error, certainly not
something that should go un-handled.

**Comment by remy-tiitre** [comment] 2017-09-20 07:06
After saving plugin settings I get into log these rows:
```
2017-09-20 10:01:32,739  INFO [qtp1651945012-33] RequestLog:37 - 10.255.0.2 - - [20/Sep/2017:07:01:32 +0000] "GET /go/api/plugin_images/cd.go.contrib.elastic-agent.docker-swarm/176f84f4804cd55e556170df3ecb88da
cf40d733077e5251b4ea6048a2257d5c HTTP/1.1" 200 -  134
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It might be something related to GoCD server setup, as when the server starts up, it gives me the following rows:
```
2017-09-20 10:01:32,739  INFO [qtp1651945012-33] RequestLog:37 - 10.255.0.2 - - [20/Sep/2017:07:01:32 +0000] "GET /go/api/plugin_images/cd.go.contrib.elastic-agent.docker-swarm/176f84f4804cd55e556170df3ecb88da
cf40d733077e5251b4ea6048a2257d5c HTTP/1.1" 200 -  134
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I do have debug level enabled:
`GO_SERVER_SYSTEM_PROPERTIES='-Dgo.console.stdout=true -Dplugin.cd.go.contrib.elastic-agent.docker-swarm.log.level=debug'`

**Comment by remy-tiitre** [comment] 2017-09-20 07:12
But building still doesnt work and it seems that the logging is broken as well. In GoCD log I get the following exception when I start pipeline that has elastic agent applied:
```
2017-09-20 10:10:54,710 ERROR [133@MessageListener for CreateAgentListener] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.Cr
eateAgentListener@6d2a32bc
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.contrib.elastic-agent.docker-swarm' implementing 'elastic-agent' extension failed while requesting for 'go.cd.elastic-agent.create-agent'. Rea
son: [java.lang.IllegalArgumentException: Invalid size: ]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:42)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:59)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:40)
        at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
        at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid size:
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:318)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
        ... 7 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid size:
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:78)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Invalid size:
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.utils.Size.parse(Size.java:83)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerService.requirements(DockerService.java:129)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerService.create(DockerService.java:105)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.create(DockerServices.java:48)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerServices.create(DockerServices.java:33)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:39)
        at cd.go.contrib.elasticagents.dockerswarm.elasticagent.DockerPlugin.handle(DockerPlugin.java:56)
        ... 13 more
```

**Comment by ketan** [comment] 2017-09-20 07:22
What did you pass in as the memory limits? It looks like parsing that has failed. We have a fix for this issue in the upcoming release. We recommend setting the size using using a an integer and a unit. (`512mb`, `2gb`, etc...)

**Comment by remy-tiitre** [comment] 2017-09-20 07:24
As you can see from the sample profile, I left them empty to make the profile as simple as possible. It doesn't say anywhere that they are mandatory.

**Comment by bdpiparva** [comment] 2017-09-20 07:33
@remy-tiitre --- server don't know much about plugin configuration it is plugins job to validate the profile. When you create a profile from config.xml server will not ask plugin to validate the profile as it is expensive call and might block config save.

Please use [Elastic Profile API](https://api.gocd.org/17.11.0/#create-an-elastic-agent-profile) or configure the profile through UI: **_Admin_** > **_Elastic Agent Profiles_**

**Comment by remy-tiitre** [comment] 2017-09-20 11:23
I created the Elastic Agent Profile from Admin > Elastic Agent Profiles page and it did not complain about memory settings missing. And That page has only "Docker image:*" marked as mandatory. But it seems that adding memory limist fixed this issue and this task can me closed.

**Closed** 2017-09-28 07:32 UTC
